[package]
name = "sim_control"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
sim_core = { path = "../sim_core" }

[dev-dependencies]
sim_core = { path = "../sim_core", features = ["test-support"] }
