[package]
name = "sim_cli"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
sim_core = { path = "../sim_core" }
sim_control = { path = "../sim_control" }
sim_world = { path = "../sim_world" }
serde_json = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
