[package]
name = "sim_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
rand = "0.8"

[lints]
workspace = true

[dev-dependencies]
rand_chacha = "0.3"
